const countryNames: { [key: string]: string } = {
    UK: 'United Kingdom',
    DE: 'Germany',
    AU: 'Australia',
    IT: 'Italy',
    VE: 'Venezuela',
    PL: 'Poland',
    US: 'United States',
    MX: 'Mexico',
    CA: 'Canada',
    BR: 'Brazil',
    FR: 'France',
    KR: 'South Korea',
    SK: 'Slovakia',
    RU: 'Russia',
    ES: 'Spain',
    NL: 'Netherlands',
    AT: 'Austria',
    FI: 'Finland',
    SE: 'Sweden',
    JP: 'Japan',
    HU: 'Hungary',
    PT: 'Portugal',
    SA: 'Saudi Arabia',
    IR: 'Iran',
    DK: 'Denmark',
    NO: 'Norway',
    CZ: 'Czech Republic',
    AR: 'Argentina',
    HR: 'Croatia',
    UA: 'Ukraine',
    SG: 'Singapore',
    IN: 'India',
    CL: 'Chile',
    BE: 'Belgium',
    GR: 'Greece',
    DO: 'Dominican Republic',
    PH: 'Philippines',
    TH: 'Thailand',
    SI: 'Slovenia',
    TW: 'Taiwan',
    AE: 'United Arab Emirates',
    TR: 'Turkey',
    CN: 'China',
    ZA: 'South Africa',
    RS: 'Serbia',
    PE: 'Peru',
    HK: 'Hong Kong',
    EG: 'Egypt',
    CO: 'Colombia',
    MY: 'Malaysia',
    CH: 'Switzerland',
    IL: 'Israel',
    RO: 'Romania',
    PR: 'Puerto Rico',
    CY: 'Cyprus',
    ID: 'Indonesia',
    IE: 'Ireland',
    HN: 'Honduras'
}

export const getCountryName = (code: string): string => {
    return countryNames[code] || code
}
